# Generated by Django 6.0.2 on 2026-03-03 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sitename", models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=350)),
                ("password", models.CharField(max_length=350)),
                (
                    "Site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pmanager.sites"
                    ),
                ),
            ],
        ),
    ]
