# Generated by Django 6.0.2 on 2026-03-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmanager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sites",
            name="sitename",
            field=models.CharField(max_length=350, unique=True),
        ),
    ]
