# Generated by Django 6.0.2 on 2026-03-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pmanager", "0002_alter_sites_sitename"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="Credentials",
        ),
    ]
