# Generated by Django 6.0.2 on 2026-03-06 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmanager", "0003_rename_users_credentials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sites",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sites",
            name="sitename",
            field=models.CharField(max_length=350),
        ),
        migrations.AlterUniqueTogether(
            name="sites",
            unique_together={("sitename", "user")},
        ),
    ]
